### ISSUE TITLE
Add support for all features in python example

### ISSUE THREAD

**Issue by rnicholus** [FineUploader/server-examples#13]

**Comment by stanislavBozhanov** [comment]
Is someone up for updating this to work on python3. I saw you put a label 2-Do two years ago.

**Comment by rnicholus** [comment]
No one, to my knowledge, has expressed interest. But I'd love to see someone step up and contribute...

**Comment by HammadHQ** [comment]
I have done bit of work in web2py

**Comment by rnicholus** [comment]
this is over a year old and no one has stepped up - closing
