### ISSUE TITLE
Server-example for S3 C#/Web API/MVC

### ISSUE THREAD

**Issue by akhilaj** [FineUploader/server-examples#41]
Hi,

It will be great if we have an example of server side C# / .net code ...

Thanks...

**Comment by rnicholus** [comment]
Unfortunately, no one on the Fine Uploader team works with a Microsoft stack, so unless someone contributes an example, I don't see this happening any time soon.

**Comment by GFoley83** [comment]
👍

**Comment by rnicholus** [comment]
Closest thing I have is a C# example for Fine Uploader Azure. Contributions welcome.

**Comment by mjeson** [comment]
+1  for this thread .

I dont mind contributing, but I am lost now. Do you have a pseudocode of what the signing method suppose to do ? A sample of input and output would work as well. I have tried to follow your blog, read the java code, php code, and the javascript code and I am lost in the details now. Each of them has different way of handling cryptography.

The cyrptographic signing process to upload from client directly to S3 looks very complicated in .NET . I am stuck there. Found an example from S3 website.
http://docs.aws.amazon.com/AmazonS3/latest/API/samples/AmazonS3SigV4_Samples_CSharp.zip
http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-examples-using-sdks.html

**Comment by rnicholus** [comment]
The https://github.com/FineUploader/php-s3-server/blob/master/endpoint.php file should give you an idea what is required to sign v4 and v2 REST requests, along with requests that contain a policy document.
