### ISSUE TITLE
Need some clarification regarding the keys.

### ISSUE THREAD

**Issue by sudipbhandari126** [FineUploader/server-examples#44]
From AWS s3 AWSAccesskey and AWSSecretkeys are provided. In the demo php server code there are 4 different keys. Which key assosciates to the given access key by aws? Also, what's the expectedhostname?

**Comment by rnicholus** [comment]
You should have a set of server keys with expanded permissions (even admin permissions if you are comfortable with that) and a set of client keys with very limited permissions (to avoid mistakes in code that would allow a malicious user to perform undesired actions on your S3 objects/bucket.

`expectedhostname` is the host name for your S3 bucket
