### ISSUE TITLE
Flysystem example

### ISSUE THREAD

**Issue by kamov** [FineUploader/server-examples#47]
There is an example using http://flysystem.thephpleague.com/
for upload file?
Thanks

**Comment by rnicholus** [comment]
Not at this time. Pull requests welcome!

**Comment by kamov** [comment]
I hope that you can make one example soon.
I have intention to buy a license if can sort out how to integrate both.
Thanks!

**Comment by rnicholus** [comment]
I'm not familiar with flysystem, but if it becomes a popular request, I'll look into providing an example. Regardless, it should be straightforward to integrate fine uploader with any system. See the documentation site for an explanation of the requests your server must handle.

**Comment by kamov** [comment]
Yes I checked documentation, and it should not be hard to integrate normal upload.
What I can't sort out is "Chunking/Partitioning" part.
Since flysystem can add file also directly to remote filesystem, I am not sure how to handle Chunking/Partitioning. But also locally.
