### ISSUE TITLE
IE 10 drag n drop issue in fineuploader

### ISSUE THREAD

**Issue by Manidipa** [FineUploader/server-examples#48]
Hi Ray

drag n drop is not working in IE 10 and edge browser

Please let me the possible solution.

Regards
Manidipa

**Comment by rnicholus** [comment]
This repo is for the serve examples code. It has nothing to do with drag and drop. Furthermore, DND has been tested in IE 10 and the latest version of edge in the latest version of Fine Uploader. If you are seeing an issue, you will need to open up a well formed and detailed issue in the fine-uploader repo.
