### ISSUE TITLE
Clarity regarding the keys in django example

### ISSUE THREAD

**Issue by maan19** [FineUploader/server-examples#54]
I have my root credentials and IAM user credentials but I am confused which to use where with respect to the following->

AWS_CLIENT_PUBLIC_KEY=?
AWS_CLIENT_SECRET_KEY=?
AWS_SERVER_PUBLIC_KEY=?
AWS_SERVER_SECRET_KEY=?
Plz help me to sort out!

**Comment by rnicholus** [comment]
http://stackoverflow.com/a/37424210/486979
