### ISSUE TITLE
Update Server-Side Examples

### ISSUE THREAD

**Issue by feltnerm** [FineUploader/server-examples#6]
- [ ] **[Python-django](https://github.com/Widen/fine-uploader-server/tree/master/python_django)** server needs dependencies listed and could be brought up to date with the latest Django. Interesting to note that the [qqFileUploader](https://github.com/Widen/fine-uploader-server/blob/master/python_django/file_uploader/__init__.py) class implements a lot of advanced functionality.
- [x] **Ruby example**
- [ ] **Bugfixes / Tests**

**Comment by pratik60** [comment]
I have used this before on both node.js and php....Think I might be able to come up with a rails example, but might need your help as well.

**Comment by rnicholus** [comment]
@pratik60 What sort of assistance do you think you may need?

**Comment by Panczo** [comment]
@pratik60 i made rails example with reactfineuploader i also made pull request.
You'd look at this [here](https://github.com/Panczo/reactfineuploader-example)

**Comment by rnicholus** [comment]
we have a rails example, no one seems to want to contribute p3. closing
