### ISSUE TITLE
 iam using FineUploaderBasic getting error on server side

### ISSUE THREAD

**Issue by ChiragDynamic** [FineUploader/server-examples#71]
Hi, I am using FineUploaderBasic for sending a video file it's returning like

[Fine Uploader 5.16.0] Received response status 502 with body: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.6.3</center>
</body>
</html>

**Comment by rnicholus** [comment]
I suggest you fix your nginx proxy then

**Comment by ChiragDynamic** [comment]
Thanks , but its resolved by adding

                uploadType:'resumable',

in youtube video insert jquery. and its working fine.
var req = youtube.videos.insert({
                uploadType:'resumable',

**Comment by rnicholus** [comment]
This has absolutely nothing to do with Fine Uploader, and this is the first time you’ve mentioned the YouTube api. Please only post Fine Uploader issues in here.
